### ISSUE TITLE
[Feature Request] Adding Support For cu12.1, RTX4090

### ISSUE THREAD

**Issue by telegraph-pole-head** [HanGuo97/flute#3]
Really appericiate ur effort!

We're testing SOTA LLM quantization and hardware optimization frameworks across different platforms and looking forward to Flute's support for **cu12.1 torch2.3** on RTX4090.

I've tried:
1. building from source
2. changing the CUTLASS_PATH in setup.py
3. `pip install -e .` and `pip install .`

get Error:
```
Building editable for flute-kernel (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for flute-kernel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [199 lines of output]
      running editable_wheel
      creating /tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info
      writing /tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel-0.0.3.dist-info'
      creating /tmp/pip-wheel-3ctols7v/.tmp-axz8fnnh/flute_kernel-0.0.3.dist-info/WHEEL
      running build_py
      running build_ext
      /tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py:428: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'flute._C' extension
      creating /tmp/tmpai2_yt5h.build-temp/flute
      creating /tmp/tmpai2_yt5h.build-temp/flute/csrc
      /tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
      If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
        warnings.warn(
      Emitting ninja build file /tmp/tmpai2_yt5h.build-temp/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/4] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_example.o.d '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_example.cu -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_example.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      FAILED: /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_example.o
      /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_example.o.d '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_example.cu -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_example.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_example.cu:3:10: fatal error: cute/tensor.hpp: No such file or directory
          3 | #include <cute/tensor.hpp>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      [2/4] c++ -MMD -MF /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm.o.d -pthread -B /home/<my wksp>/.conda/envs/nvllm/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/<my wksp>/.conda/envs/nvllm/include -fPIC -O2 -isystem /home/<my wksp>/.conda/envs/nvllm/include -fPIC '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm.cpp -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm.o -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm.o
      c++ -MMD -MF /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm.o.d -pthread -B /home/<my wksp>/.conda/envs/nvllm/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/<my wksp>.conda/envs/nvllm/include -fPIC -O2 -isystem /home/<my wksp>/.conda/envs/nvllm/include -fPIC '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm.cpp -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm.o -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      /home/<my wksp>/download/flute/flute/csrc/qgemm.cpp:7:10: fatal error: cute/numeric/integral_constant.hpp: No such file or directory
          7 | #include "cute/numeric/integral_constant.hpp"
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      [3/4] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_generated.o.d '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_generated.cu -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_generated.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      FAILED: /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_generated.o
      /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_generated.o.d '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_generated.cu -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_generated.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_generated.cu:4:10: fatal error: cute/tensor.hpp: No such file or directory
          4 | #include <cute/tensor.hpp>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      [4/4] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_raw_generated.o.d '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_raw_generated.cu -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_raw_generated.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      FAILED: /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_raw_generated.o
      /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_raw_generated.o.d '-I~/download/cutlass/include' '-I~/download/cutlass/tools/util/include' -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/TH -I/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/<my wksp>/.conda/envs/nvllm/include/python3.10 -c -c /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_raw_generated.cu -o /tmp/tmpai2_yt5h.build-temp/flute/csrc/qgemm_kernel_raw_generated.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      /home/<my wksp>/download/flute/flute/csrc/qgemm_kernel_raw_generated.cu:4:10: fatal error: cute/tensor.hpp: No such file or directory
          4 | #include <cute/tensor.hpp>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
          subprocess.run(
        File "/home/<my wksp>/.conda/envs/nvllm/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 153, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
          build_ext.build_extensions(self)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      /tmp/pip-build-env-oh1azyns/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:989: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `flute-kernel` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
```

**Comment by HanGuo97** [comment]
Hi, thanks for trying it out! The error message seems like either (1) CUTLASS is not found, and (2) you have a wrong version of CUTLASS (v3.4.1).

That being said, I think the main challenge for supporting RTX4090 is that we tuned kernel configurations for A6000/A100 only, and need to tune them separately for RTX4090. How important is 4090 to you? If it's critical, we are happy to work on it in the next few days. (It's in our roadmap, anyway.)

**Comment by telegraph-pole-head** [comment]
Thanks for your timely response!
I changed the `CUTLASS_PATH` from `~/blabla` to `/home/<mywksp>/blabla` and it works.
Though successfully build and install flute, I still get NotImplementedError which I guess is because 4090 is not supported yet.
A soon perview release supporting 4090 will be highly appreciated.
Also very exciting to see the tuned kernel's performance on 4090 in the (hopefully near) future!

**Comment by HanGuo97** [comment]
Great! I can try to get that in about a week. The main bottleneck is that I don't personally have access to 4090...

**Comment by radi-cho** [comment]
If having only two 4090s is not a bottleneck for tuning the kernel, we can use my personal GPUs to release 4090 support.

**Comment by HanGuo97** [comment]
@telegraph-pole-head Just want to let you know that we have pushed an update to support RTX4090 GPUs. Please give it a try and let us know if it works!
